version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ui
    ports:
      - "3002:5173"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

    ports:
      - 5433:5432  
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:


## https://www.youtube.com/watch?v=qECVC6t_2mU&ab_channel=Randomcode