FROM python:3.9
WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev
COPY /app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt 
COPY . /app/

# Copy and set the entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

